baseurl = "https://namespace.gitlab.io"
title = "My blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "DevDar Blog"
    description = "Shared coding stories"
#    facebook = "https://github.com/XXX"
#    twitter = "https://twitter.com/XXX"
    email = "dariusz.mozgowoj@gmail.com"
    rss = true
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
